site_name: Cheatsheets
theme:
  name: material
  language: en
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  icon:
    edit: material/pencil
  features:
    - content.action.edit
    - navigation.instant
    - search.suggest
    - search.highlight

repo_name: 'woernfl/cheatsheets'
repo_url: 'https://github.com/woernfl/cheatsheets'

copyright: 'Copyright &copy; 2017 - 2023 Florian Woerner'

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://blog.woernfl.xyz/
      name: Woernfl's blog
    - icon: fontawesome/brands/github
      link: https://github.com/woernfl
      name: Woernfl on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/woernfl
      name: Woernfl on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/woernfl
      name: Woernfl on Linkedin
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.


markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

plugins:
  - social
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
      locale: en
